stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t living-parallax .
    - docker run --rm -p 8000:80 living-parallax
  artifacts:
    paths:
      - my-app-image.tar