stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

build_job:
  image: docker:24
  services:
    - docker:24-dind
  stage: build
  script:
    - docker build -t living-parallax .
    - docker save living-parallax -o my-app-image.tar
  artifacts:
    paths:
      - my-app-image.tar
    expire_in: 1h

deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Add deploy steps here (push image to registry or deploy to server)"